name: 'Run Discipline'

on:
  schedule:
    - cron: '21 1-3,8-11,13-17,20-23 * * *'
  watch:
    types: started
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    if: github.repository != 'happy888888/BiliExp' || github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v2
      with: 
        repository: ${{ secrets.REPOSITORY }}
        ref: ${{ secrets.REF }}

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Discipline
      run: bash ./run_in_Actions/run_BiliExp.sh
      env:
          ADVCONFIG: ${{ secrets.ADVCONFIG }}
          BILICONFIG: ${{ secrets.BILICONFIG }}
          PUSH_MESSAGE: ${{ secrets.PUSH_MESSAGE }}
          DELAY: ${{ secrets.DELAY }}
